/*
MIT License

Copyright (c) 2022 Neel Apte

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

package com.neel.payroll;

import com.neel.payroll.VM.EmployeeDE4TabVM;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;

/**
 *
 * @author Neel
 */
public class CA_De4_Dlg extends javax.swing.JDialog {

    private int employeeId = 0;
    
    /**
     * Creates new form CA_De4_Dlg
     */
    public CA_De4_Dlg(java.awt.Frame parent, boolean modal, int employeeId) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); //Center dialog in screen
        this.employeeId = employeeId;
        EmployeeDE4TabVM.FillUI(this, employeeId);
    }

        public JComboBox<String> getCaDE4FilingStatus() {
        return caDE4FilingStatus;
    }

    public JSpinner getCaDE4_Line1A_RegAllowance() {
        return caDE4_Line1A_RegAllowance;
    }

    public JSpinner getCaDE4_Line1B_EstAllowance() {
        return caDE4_Line1B_EstAllowance;
    }

    public JCheckBox getChkCA_DE4_Exempt() {
        return chkCA_DE4_Exempt;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkCA_DE4_Exempt = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        caDE4FilingStatus = new javax.swing.JComboBox<>();
        cade4UpdateBtn = new javax.swing.JButton();
        caDE4_Line1A_RegAllowance = new javax.swing.JSpinner();
        caDE4_Line1B_EstAllowance = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chkCA_DE4_Exempt.setText("EXEMPT");

        jLabel1.setText("Line 1A Regular Allowance:");

        jLabel2.setText("Line 1B Estimated Ded Allowance");

        jLabel3.setText("Filing Status");

        caDE4FilingStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "H" }));

        cade4UpdateBtn.setText("Update");
        cade4UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cade4UpdateBtnActionPerformed(evt);
            }
        });

        caDE4_Line1A_RegAllowance.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        caDE4_Line1B_EstAllowance.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCA_DE4_Exempt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caDE4FilingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(caDE4_Line1B_EstAllowance, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(caDE4_Line1A_RegAllowance, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(cade4UpdateBtn)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkCA_DE4_Exempt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(caDE4_Line1A_RegAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(caDE4FilingStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(cade4UpdateBtn))
                    .addComponent(caDE4_Line1B_EstAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cade4UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cade4UpdateBtnActionPerformed
        EmployeeDE4TabVM.SaveDE4(this, CA_De4_Dlg.this.employeeId);
        setVisible(false);
    
    }//GEN-LAST:event_cade4UpdateBtnActionPerformed



   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> caDE4FilingStatus;
    private javax.swing.JSpinner caDE4_Line1A_RegAllowance;
    private javax.swing.JSpinner caDE4_Line1B_EstAllowance;
    private javax.swing.JButton cade4UpdateBtn;
    private javax.swing.JCheckBox chkCA_DE4_Exempt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
